### ISSUE TITLE
rEFInd doesn't recognize the theme

### ISSUE THREAD

**Issue by TheRealGramdalf** [JPUnD/refind-ambience-deer-and-fireflies#1]
The theme is not recognized when following the instructions given on the main github page; the folder in the `include /path/to/thing.conf` is called `refind-ambience-remake`, not `refind-ambience-deer-and-fireflies`

**Comment by jpmvferreira** [comment]
You're right, thanks for the information.

Fixed in 205315f758d6e4d71134c05db0177f2824a01ae4
